---
- name: Add cron daily backup task
  cron:
    name: "Backup OpenStack"
    minute: "{{ osa_backup_cron_minute }}"
    hour: "{{ osa_backup_cron_hour }}"
    day: "{{ osa_backup_cron_day }}"
    month: "{{ osa_backup_cron_month }}"
    weekday: "{{ osa_backup_cron_weekday }}"
    job: "{{ osa_backup_cron_command }}"
  tags:
    - openstack-backup-cron
